- block:
     - name: yum repository
       yum_repository:
          name: testserver
          baseurl: http://192.168.72.72/rhel7.6
          enabled: yes
          gpgcheck: no
          description: testserver

  rescue:
     - name: yum clean all
       shell:
          cmd: /usr/bin/yum clean all; /usr/bin/yum repolist
  always:

     - name: yum install
       yum:
          name: ['@^graphical-server-environment', '@base', '@compat-libraries', '@desktop-debugging', '@dial-up', '@fonts', '@gnome-desktop', '@guest-agents', '@guest-desktop-agents', '@hardware-monitoring', '@input-methods', '@internet-browser', '@large-systems', '@multimedia', '@performance', '@print-client', '@system-admin-tools', '@x11', 'libaio', 'libaio-devel', 'elfutils-libelf-devel', 'libgcc', 'libstdc++', 'libstdc++-devel', 'ntp', 'sysfsutils', 'uuidd', 'ksh', 'unixODBC', 'unixODBC-devel', 'xinetd', 'libstdc++.i686']
          state: present

     - name: yum remove
       yum:
          name: net-snmp
          state: absent
