- name: cmdline for dell
  lineinfile:
     path: /etc/default/grub
     regexp: '^GRUB_CMDLINE_LINUX='
     line: 'GRUB_CMDLINE_LINUX="nmi_watchdog=0 transparent_hugepage=never elevator=deadline rdloaddriver=megaraid_sas rdloaddriver=lpfc crashkernel={{ kdump_mem }} ipv6.disable=1 mce=ignore_ce intel_idle.max_cstate=0 processor.max_cstate=1 intel_pstate=disable nosoftlockup"'
  notify:
     - reconfiguration of grub
