- name: sysctl.conf
  blockinfile:
     path: /etc/sysctl.conf
     marker: "{mark}"
     marker_begin: "  "
     marker_end: "   "
     block: |
        kernel.sysrq = 1
        kernel.panic_on_io_nmi = 1
        kernel.panic_on_unrecovered_nmi = 1
        kernel.unknown_nmi_panic = 1
        kernel.core_pattern = /CRASH/core_%e_%p_%h_%u_%t
        kernel.pid_max = 120000
        net.ipv4.ip_forward = 0
        net.ipv4.conf.default.accept_source_route = 0
        net.ipv6.conf.all.disable_ipv6 = 1 
        net.core.somaxconn = 8192
        net.ipv4.tcp_max_syn_backlog = 8192
        vm.dirty_ratio = 40 
        vm.dirty_background_ratio = 10 
        vm.swappiness = 10 
  when: bool_phy == 'phy'


- name: sysctl.conf
  blockinfile:
     path: /etc/sysctl.conf
     marker: "{mark}"
     marker_begin: "  "
     marker_end: "   "
     block: |
        kernel.sysrq = 1
        kernel.panic_on_io_nmi = 1
        kernel.panic_on_unrecovered_nmi = 1
        kernel.unknown_nmi_panic = 1
        kernel.core_pattern = /CRASH/core_%e_%p_%h_%u_%t
        kernel.pid_max = 120000
        net.ipv4.ip_forward = 0
        net.ipv4.conf.default.accept_source_route = 0
        net.ipv6.conf.all.disable_ipv6 = 1 
        net.core.somaxconn = 8192
        net.ipv4.tcp_max_syn_backlog = 8192
        vm.dirty_ratio = 30 
        vm.swappiness = 30 
  when: bool_phy == 'vm'
