- name: kdump config
  block:

     - name: kdump.conf
       block:
          - lineinfile:
               path: /etc/kdump.conf
               regexp: 'path /var/crash$'
               line: '# path /dev/vg9/DUMP'

          - lineinfile:
               path: /etc/kdump.conf
               regexp: '^raw'
               insertafter: '^#raw'
               line: '^raw /dev/vg9/DUMP'

          - replace:
               path: /etc/kdump.conf
               regexp: 'core_collector makedumpfile -l --message-level 1 -d 31'
               replace: 'core_collector makedumpfile -c -d 31 -F'

     - name: kdumpctl
       lineinfile:
          path: /usr/bin/kdumpctl
          regexp: 'save_raw$'
          line: '       # save_raw'


     - name: sysctl/kdump
       lineinfile:
          path: /etc/sysconfig/kdump
          regexp: '^KDUMP_COMMANDLINE_APPEND='
          line: 'KDUMP_COMMANDLINE_APPEND="irqpoll nr_cpus=6 disable_cpu_apicid=0 reset_devices cgroup_disable=memory mce=off numa=off udev.children-max=2 panic=10 rootflags=nofail acpi_no_memhotplug transparent_hugepage=never rd.driver.blacklist=RedCastle"'

