- name: ntp conf
  block:
    
    - template:
          src: templates/ntp.conf.j2
          dest: /etc/ntp.conf

- name: ntp in sysconfig 
  lineinfile:
     path: /etc/sysconfig/ntpd
     regexp: '^OPTIONS='
     line: 'OPTIONS="-g -4 -x"'
